name       : emacs
version    : '28.1'
release    : 27
source     :
    - https://github.com/emacs-mirror/emacs/archive/refs/tags/emacs-28.1.tar.gz : a0236a44946fdb67b037041b354ea1aa6657f04067f17fbbe16dd2e09babc843
license    : GPL-3.0-or-later
component  : editor
summary    : An extensible, customizable text editor—and more
description: |
    GNU Emacs is an extensible, customizable text editor—and more. At its core is an interpreter for Emacs Lisp, a dialect of the Lisp programming language with extensions to support text editing. It has many features to increase productivity when programming.
builddeps  :
    - pkgconfig(gconf-2.0)
    - pkgconfig(gnutls)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(harfbuzz)
    - pkgconfig(jansson)
    - pkgconfig(libacl)
    - pkgconfig(libturbojpeg)
    - pkgconfig(libxml-2.0)
    - pkgconfig(webkit2gtk-4.0)
    - pkgconfig(xpm)
    - giflib-devel
    - gpm-devel
    - xorgproto
optimize   : speed
conflicts  :
    - ctags
setup      : |
    ./autogen.sh autoconf
    %configure --enable-acl --with-json  --with-xwidgets --with-x-toolkit=gtk3 --with-xinput2 --without-xaw3d --with-sound=no --with-modules --without-libotf --without-m17n-flt --enable-link-time-optimization
build      : |
    %make
install    : |
    %make_install
