name       : emacs
version    : 24.5
release    : 3
source     :
    - http://ftp.gnu.org/gnu/emacs/emacs-24.5.tar.xz : dd47d71dd2a526cf6b47cb49af793ec2e26af69a0951cc40e43ae290eacfc34e
license    : GPL-2.0+
summary    : An extensible, customizable text editor—and more
description: |
    GNU Emacs is an extensible, customizable text editor—and more. At its core is an interpreter for Emacs Lisp, a dialect of the Lisp programming language with extensions to support text editing. It has many features to increase productivity when programming.
builddeps  :
    - pkgconfig(atk)
    - pkgconfig(gtk+-2.0)
    - pkgconfig(libpng15)
    - pkgconfig(libtiff-4)
    - pkgconfig(pangocairo)
    - pkgconfig(x11)
    - pkgconfig(xaw3d)
    - pkgconfig(xpm)
    - pkgconfig(xft)
    - giflib-devel
    - libjpeg-turbo-devel
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
