name       : emacs
version    : '26.1'
release    : 16
source     :
    - https://ftp.gnu.org/gnu/emacs/emacs-26.1.tar.xz : 1cf4fc240cd77c25309d15e18593789c8dbfba5c2b44d8f77c886542300fd32c
license    : GPL-3.0-or-later
component  : editor
summary    : An extensible, customizable text editor—and more
description: |
    GNU Emacs is an extensible, customizable text editor—and more. At its core is an interpreter for Emacs Lisp, a dialect of the Lisp programming language with extensions to support text editing. It has many features to increase productivity when programming.
builddeps  :
    - pkgconfig(gconf-2.0)
    - pkgconfig(gnutls)
    - pkgconfig(librsvg-2.0)
    - pkgconfig(libtiff-4)
    - pkgconfig(libturbojpeg)
    - pkgconfig(webkit2gtk-4.0)
    - pkgconfig(xaw3d)
    - pkgconfig(xpm)
    - pkgconfig(xft)
    - ctags
    - giflib-devel
rundeps    :
    - ctags
setup      : |
    %patch -p1 < $pkgfiles/0001-fix-hunspell-1.7.0.patch
    %configure --with-modules --with-xwidgets --with-x-toolkit=gtk3
build      : |
    %make
install    : |
    %make_install
    rm $installdir/usr/bin/ctags
    rm $installdir/usr/share/man/man1/ctags*
