name       : emacs
version    : '25.2'
release    : 7
source     :
    - http://ftp.gnu.org/gnu/emacs/emacs-25.2.tar.xz : 59b55194c9979987c5e9f1a1a4ab5406714e80ffcfd415cc6b9222413bc073fa
license    : GPL-2.0+
component  : editor
summary    : An extensible, customizable text editor—and more
description: |
    GNU Emacs is an extensible, customizable text editor—and more. At its core is an interpreter for Emacs Lisp, a dialect of the Lisp programming language with extensions to support text editing. It has many features to increase productivity when programming.
builddeps  :
    - pkgconfig(atk)
    - pkgconfig(gtk+-2.0)
    - pkgconfig(libpng15)
    - pkgconfig(libtiff-4)
    - pkgconfig(pangocairo)
    - pkgconfig(x11)
    - pkgconfig(xaw3d)
    - pkgconfig(xpm)
    - pkgconfig(xft)
    - giflib-devel
    - libjpeg-turbo-devel
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
